### PR TITLE
feature: add functionality to fetch and format food recall data

### PR DESCRIPTION
**Pull request by lucy-schafer**
This PR adds a new functionality to fetch food recall data from the FDA API for a given date range.
It also includes parsing logic to format the retrieved data into a list of dictionaries with key details for each recalled product returned from the API get response.

### CODE REVIEW

**Comment by lucy-schafer** [comment]
@css186 Ready for review. I had to do some data cleansing to test the functionality of the API get request. I made a judgement call on which details we'd actually want to store in our food recall database. Let me know if you think any recall details are unnecessary or if we need to include more. I'm happy to collaborate further on this and/or if more data cleansing is needed.

**Comment by css186** [comment]
@lucy-schafer 
I have two questions:
1. I want to know the reason why you decided to go with 100 on the "limit" parameter instead of max value (i.e. 1000)
2. so the formatFoodRecalls function is for the judgment call?

**Comment by css186** [comment]
@lucy-schafer Code reviewed. Changes were made according to our discussion, so it looks good to me.

**Comment by css186** [comment]
@lucy-schafer 
I've noticed that you place the getFoodRecalls and formatFoodRecalls functions inside the controller directory.
Would you mind moving them into the lambda functions directory since we will turn them into lambda functions ultimately?
I'm so sorry that I didn't explain the structure in detail so well, so that's on me.

**Comment by lucy-schafer** [comment]
@css186, yes sorry about that. I just moved it under the lambda directory and renamed it accordingly. Let me know how that looks. Also, I did some research and did not find any evidence that the FDA has ever reported more than 1000 food recalls in one week, so I won't be adding the skip to the search query to keep the code as simple as possible!

**Comment by css186** [comment]
@lucy-schafer Thank you so much! As for the skip parameter part, I'm okay with that.
I will go ahead and merge your part into the code base

**Pull request merged**
